### ISSUE TITLE
Adding thin space to the keyboard 

### ISSUE THREAD

**Issue by goorgoor** [simple-keyboard/simple-keyboard-layouts#749] opened 2020-10-25 13:38 UTC
Hi there,

So i'm trying to edit this keyboard based on the farsi edition. What i miss is \u200C also known as Unicode Character 'ZERO WIDTH NON-JOINER'. I can add it and it works, but cant turn my head around visualising it like in this picture from a iOs keyboard. 

So my question is how can i add an image like caps or shift to it?

[](url)
![e967a077-5dcc-4ac1-a7f0-74b5e0faec0b](https://user-images.githubusercontent.com/19527211/97108741-ac519080-16cf-11eb-9227-1959d4df0bc7.jpeg)

**Comment by hodgef** [comment] 2020-10-25 21:27
Duplicate of #433.

Check out this comment in specific, it should help https://github.com/hodgef/simple-keyboard/issues/433#issuecomment-591654252

Let me know if you still have issues - Thanks!

**Comment by hodgef** [comment] 2020-10-25 21:28
Duplicate of #433

**Comment by hodgef** [comment] 2020-10-25 21:29
Check out this comment in specific, it should help hodgef/simple-keyboard#433 (comment)
Let me know if you still have issues - Thanks!

**Closed by hodgef** 2020-10-25 21:29 UTC

**Comment by goorgoor** [comment] 2020-11-01 22:07
thanks for your reply, but i dont see how i can add "\u200C" to this part? 

can you please provide with an example?

**Comment by hodgef** [comment] 2020-11-01 23:21
I think the [docs for the display property](https://codesandbox.io/s/flamboyant-matsumoto-mijnl?file=/src/index.js) is pretty straightforward. What part is not clear?

You'd basically need to add your key to your layout, then use the `display` option to change how that key will be displayed in the keyboard.

https://codesandbox.io/s/flamboyant-matsumoto-mijnl?file=/src/index.js

Regards,
Francisco Hodge
